name: Node.js CI

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8

        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb

        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      NODE_OPTIONS: --dns-result-order=ipv4first
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/testdb
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Install CA certificates
        run: sudo apt-get update && sudo apt-get install -y ca-certificates

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Check Prisma version
        run: npx prisma -v

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Push database schema
        run: npx prisma db push --accept-data-loss

      - name: Run tests
        run: npm test
